backend:
    name: proxy
    repo: pratik-kanthi/cab9.website
    branch: develop
    proxy_url: http://localhost:8081/api/v1

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
    - name: 'Blog'
      label: 'Blog'
      folder: 'blog'
      create: true
      slug: '{{slug}}'
      format: 'json'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
          - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
          - { label: 'Publish Date', name: 'date', widget: 'date', format: 'MMM DD, YYYY' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'Author Image', name: 'authorImage', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    - name: 'Testimonial'
      label: 'Testimonial'
      format: json
      folder: 'testimonials'
      slug: '{{slug}}'
      create: true
      fields:
          - { label: 'Person Name', name: 'person_name', widget: 'string' }
          - { label: 'Testimonial Text', name: 'testimonial_text', widget: 'string' }
